<?php

return [
    'smtp' => [
        'host' => 'smtp.transip.email',
        'port' => 587,
        'encryption' => 'tls',
        'username' => 'info@vectorworks-spotlight-training.nl',
        'password' => 'replace-with-real-password',
        'timeout' => 15,
    ],
    'mail' => [
        'from_email' => 'info@vectorworks-spotlight-training.nl',
        'from_name' => 'STB Services',
        'to_email' => 'info@vectorworks-spotlight-training.nl',
        'subject_prefix' => '',
        'review_prefix' => '[Review]',
    ],
    'altcha' => [
        'enabled' => true,
        'hmac_signature_secret' => 'replace-with-a-long-random-secret',
        'challenge_expires_seconds' => 600,
        'pbkdf2_cost' => 1000,
        'key_length' => 32,
        'key_prefix' => '00',
    ],
    'security' => [
        'min_submit_seconds' => 3,
        'max_attempts_per_window' => 5,
        'window_seconds' => 900,
        'max_attempts_per_email_window' => 3,
        'email_window_seconds' => 3600,
        'max_attempts_per_ip_ua_window' => 6,
        'ip_ua_window_seconds' => 1800,
        'score_flag_threshold' => 30,
        'score_block_threshold' => 70,
        'max_links' => 2,
        'max_name_length' => 120,
        'max_company_length' => 160,
        'max_phone_length' => 60,
        'max_email_length' => 254,
        'max_address_length' => 200,
        'max_city_length' => 120,
        'max_postal_code_length' => 32,
        'max_message_length' => 5000,
        'enable_mx_check' => false,
        'disposable_domains_file' => 'lists/disposable_domains.txt',
    ],
];
